apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE USER IF NOT EXISTS 'spring'@'%' IDENTIFIED BY 'spring123';
    GRANT ALL PRIVILEGES ON springdb.* TO 'spring'@'%';
    FLUSH PRIVILEGES;
  grant-privileges.sh: |
    #!/bin/bash
    set -e
    echo "Waiting for MySQL to be ready..."
    until mysqladmin ping -h localhost -uroot -proot123 --silent; do
      sleep 2
    done
    echo "MySQL is ready. Granting privileges..."
    mysql -uroot -proot123 <<EOF
    CREATE USER IF NOT EXISTS 'spring'@'%' IDENTIFIED BY 'spring123';
    GRANT ALL PRIVILEGES ON springdb.* TO 'spring'@'%';
    FLUSH PRIVILEGES;
    SELECT User, Host FROM mysql.user WHERE User='spring';
    EOF
    echo "Privileges granted successfully!"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root123
            - name: MYSQL_DATABASE
              value: springdb
            - name: MYSQL_USER            # FIX: User for Spring App
              value: spring
            - name: MYSQL_PASSWORD         # FIX: Password for Spring App
              value: spring123
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-scripts
              mountPath: /scripts
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - |
                    chmod +x /scripts/grant-privileges.sh
                    /scripts/grant-privileges.sh
      volumes:                            # <-- FIX: Corrected indentation of volumes
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-init
          configMap:
            name: mysql-init
        - name: mysql-scripts
          configMap:
            name: mysql-init
            defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP