apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/springdb
  SERVER_PORT: "8080"

---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c3ByaW5n      # "spring" (base64)
  SPRING_DATASOURCE_PASSWORD: c3ByaW5nMTIz  # "spring123" (base64)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: kaaboura20/devopsatelier:v16
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: devops
spec:
  selector:
    app: spring-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

